name: Deploy Reflex App to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Configura el repositorio.
      - name: Checkout Code
        uses: actions/checkout@v3

      # Configura Python.
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Instala Reflex y dependencias.
      - name: Install Reflex
        run: |
          python -m pip install --upgrade pip
          pip install reflex==0.6.5
          pip install -r requirements.txt

      # Exporta la aplicación Reflex.
      - name: Export Reflex App
        run: reflex export --frontend-only --no-zip

      # Corregir las rutas absolutas con el script
      - name: Fix absolute paths to relative
        run: |
          python fix_paths_deploy.py

      # Despliega en GitHub Pages.
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.web/_static
